AdobeDocs/analytics-2.0-apis

- README.md
- manifest-docs.json
The links were not correct and the page was not added to the manifest
> Adding Segment guide to Adobe.io

- manifest-docs.json
Since this wasn't added to the manifest it was not showing up in the UI and links to it were broken.
> Making Page Render in Adobe.io

- support.md
Super minor change to fix my own mistake - apparently it's spelled GitHub _:shrug:_
> Fix the spelling of Github to GitHub

- segments-guide.md
simple typo, the code section looks like it ended too early
simple md typo
no issue
typo
not tested
trivial documentation change
> typo: code section ends early

- manifest-docs.json
Fixing a broken link in the adobe.io docs
> adding discovery to the manifest

- segments.md
Based on a conversion in #measure slack this morning. The function is supposed to be `streq-in`, and not `streq-any-of`.
> Update comparison function

- reporting-guide.md
Breakdown filters support for item value in the filter body
This is an update to the documentation related to this story: https://jira.corp.adobe.com/browse/AN-247254
Also, fixes a documentation error in the request body of breakdown filter
https://jira.corp.adobe.com/browse/AN-247254
> AN-249148: item value support in breakdown filters

- bdia.md
be provisioned before use.  A few clients failed to notice this direction before implementation.
> More obvious call-out that ECID seed functionality must..

- src/pages/guides/endpoints/bulk-data-insertion/endpoints.md
We have had clients in the past try to run every single file through validate before sending to events, trying to avoid that through doc clarity.
> Need stronger callout of validation endpoint usage.

- docs/swagger.json
Update API JSON schema to use a more strict definition.
`ReportFilter`'s `segmentDefinition` to use `AnalyticsSegmentDefinition`.
#357
Find more accurate information about the data schema you can use in request body of reports API.
> Use the AnalyticsSegmentDefinition for ReportFilter's segmentDefinition

- src/pages/guides/endpoints/data-repair/job.md
The report suite job list endpoint now limits it's response to the last 20 jobs.
> Documenting job limit

- src/pages/guides/endpoints/dimensions/index.md
Taking @gigazelle advice in part on this and changing my mind. The fact that both request and response example appear at same place in layout make the ordering considerations a bit different than I was used to. As a result, I'm putting the both examples first and then adding parameters. I'm also changing the org a bit in other ways as the parameter section is now a sub-unit of each example details section.
> Update flow of example info

- src/pages/guides/endpoints/classifications/import-file.md
- src/pages/guides/endpoints/classifications/index.md
> Format improvements

- src/pages/guides/endpoints/bulk-data-insertion/endpoints.md
Endpoint domains for direct cluster processing have been renamed to be more region generic.  The old ones are still supported for backwards compatibility, but will no longer be documented.
> Change domain for BDIA direct cluster processing to generic names

- docs/swagger.json
- Added `includeForecasting` to RankedSettings in the request.
- Added `dataForecasted`, `dataForecastedUpperBound` and `dataForecastedLowerBound` in the response. These will be populated for all rows corresponding to future dates if the request has `includeForecasting` enabled (Meaning this is forecasting request).
More info here:
https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=scservices&title=Data+Forecasting+in+CJA
> AN-341340 Add forecasting related changes to reports endpoint

- docs/swagger.json
This change adds a new endpoint /reports/realtime which is available only for Analytics customers. This is planned as a replacement for the 1.4 real time time api.
> AN-335075 Add realtime report endpoint for analytics

- docs/classification.json
We added one API endpoint in Classification 2.0 APIs. This API is used to retrieve jobs for one classification dataset.
> AN-343425: Classification API 2.0: add one endpoint to retrieve jobs for one classification dataset

- docs/classification.json
We added two API endpoints in Classification 2.0 APIs. These APIs are used to retrieve job file section
> AN-343425: Classification API 2.0: add two endpoints to retrieve job file section

- yarn.lock
Reverts AdobeDocs/analytics-2.0-apis#467
> Revert "Bump follow-redirects from 1.15.5 to 1.15.6"

- package.json
- yarn.lock
Reverts AdobeDocs/analytics-2.0-apis#502
> Revert "Bump @adobe/gatsby-theme-aio from 4.11.3 to 4.11.15"

- docs/swagger.json
For real time reports, currently we only support dateRange which has absolute date range value for example `2024-01-01T00:00:00.000/2024-01-21T00:00:00.000`.
With this addition we support dateRangeRelative which will be of the format `from / to`. For example `20 minutes ago / now`. Below are the possible values for from and to.
- minutes i.e. "20 minutes ago"
- hours i.e. "1 hour ago"
- "now"
- "midnight"
- "noon"
- n AM/PM i.e. "3:45 PM" or "3 PM"
- yesterday n AM/PM i.e. "yesterday 12:30 PM" or "yesterday 12 PM"
> AN-333363 Add support for relative dates for real time reports

- yarn.lock
Reverts AdobeDocs/analytics-2.0-apis#520
> Revert "Bump dompurify from 2.4.0 to 2.5.6"

- yarn.lock
Reverts AdobeDocs/analytics-2.0-apis#517
> Revert "Bump micromatch from 4.0.5 to 4.0.8"

- docs/cjamigration.json
Added the swagger specifications for some selective asset migration APIs such as /projects, /mapping/dimensions/csv and /mapping/metrics/csv
> Add swagger file for some asset-migration APIs

- docs/classification.json
Classification API 2.0 Swagger: add action property for json import endpoint
Current json import endpoint swagger doesn't show "action" in the request body, update swagger document
> AN-369019: Classification API, add "action" property for json import endpoint
