manifest-stage.json
Adding a manifest in order to render docs on Adobe I/O Website stage env.
N/A
Onboarding content on Adobe I/O Website
N/A will be tested in stage and edited accordingly.
- [X ] New feature (non-breaking change which adds functionality)
N/A
=> Create manifest-stage.json for Adobe I/O Website

classifications-guide.md, oauth-postman.md
The Adobe.io site isn't as forgiving on the github flavored markdown rendering
This change should make these pages look better in that UI.
=> Fixing issues that break adobe.io rendering

README.md
=> Add note about swagger ui only supporting Adobe IDs for now

docs/swagger.json
Exposes additional segments endpoints: create, update, validate, delete.
Allows API users to have more control over management of their segments.
=> Exposes additional segments endpoints: create, update, validate, delete.

docs/swagger.json
Reverts AdobeDocs/analytics-2.0-apis#13
=> Revert "Exposes additional segments endpoints: create, update, validate, delete."

manifest-docs.json
The classification feature is not getting released yet.
=> Removing classification nav

README.md
Not sure why anchor tags are here since they don't appear to be functional
=> fixing formatting

reporting-guide.md
I've revised the reports guide. Please note that a few items contain markdown specific for Adobe I/O rendering (not Github), such as the SEO info. This is per the "collaborative documentation model" instructions.
This is a documentation change.
=> Global revision

reporting-guide.md
=> Removed mid topic links

reporting-guide.md
The curl request seems incorrect as it is missing headers and company_id information. Fixed it with successfully tested curl request.
=> Fixed curl request

oauth-postman.md
Scopes should be comma separated, I have seen people facing issue because of scopes were space separated.
In the last Time to First Hello World, one of the developer could not generate an access token using space separated scopes. When he changed the scopes to be comma separated it worked fine. I would suggest that we change our documentation to comma separated scopes which works in all scenario.
=> Updated scopes

README.md
Based on the Time To First Hello World test we did on November 13th, we observed that the Swagger UI is being ignored by developers as the current Swagger description doesn't encourages developers and it is missing essential information that one can actually explore the APIs and can make API calls within UI. I got inspiration from https://stripe.com/docs to change the wording such that developers can get the actual sense out of it.
=> Changing Swagger Description

reporting-guide.md
This formatting is not per Adobe I/O but another model and was applied mistakenly. It is now removed.
=> Remove SEO info and Note formatting

oauth-postman.md
=> Adjusted table formatting

oauth-postman.md
I changed the final sentence about getting a response in Postman so that it is not just in the context of getting a response from the users endpoint. Now, hopefully, it includes the idea you can work with any 2.0  endpoint now that Oauth is achieved in Postman.
=> Edit final sentence to improve clarity

create-oauth-client.md
I've had multiple questions and request on what these fields mean and how to fill them out. As a result, I've included more information and hopefully more clarity so that client creation goes more smoothly. This information came from general resources and the IMS wiki.
=> Added info on redirect URIs

manifest-docs.json
Changed           "path": "AdobeDocs/analytics-2.0-apis/master/segments.md",
to             "path": "AdobeDocs/analytics-2.0-apis/master/segments-guide.md",
=> updated path to segments guide

docs/swagger.json
Exposes addition segments endpoints: create, update, validate, delete.
=> Exposes addition segments endpoints: create, update, validate, delete.

calculatedmetrics.md
I have removed the POST examples from this document per the request of Ankit. Instead I have provided a sample curl GET request. This is a temporary change. I will add a sample response too, and later hopefully provide an entire guide on all the methods. But this is a quick change so that customers are not confused about POST for this being currently supported.
=> Update to remove POST

oauth-curl.md
This change includes the following style revisions:
Re-organization of steps and language for ease of readability.
Bracketing for URI placeholding paraemeters
Ordering sequence
Formatting for consistency
Spelling and syntax
Other stylistic changes
=> Style Revision for Oauth using cURL

oauth-curl.md
Edit formatting of a few items
Simply added backticks to a 2 items and fixed a lower-case letter typo
Makes the documentation clearer
Markdown renderer correctly displays the changes
=> Update formatting of a few items in oauth-curl.md

README.md, jwt.md, manifest-docs.json
We are targeting February 8th to have everything working in Production for the JWT Authentication flow. @johnwight - Could you review the wording on this but don't merge it yet. Thanks!
=> DO NOT MERGE UNTIL Admin Console changes are live (2/13 target) - Added docs about JWT

oauth-curl.md
There shouldn't be a trailing E on the client_id
=> updating to fix curl typo

reporting-tricks.md
Two updated images will also need to be added to the repo images with these textual changes
=> Updated changes per Jira AN-176665

faq.md, manifest-docs.json, support.md
The intention behind this pull request is to help developers find official and community support for Adobe Analytics.
- The FAQ page (`faq.md`) is a knowledge base that you can be organically populated with common questions (or removed if it is not desired).
- The Support page (`support.md`) is a list of support channels that developers can use to ask questions and find answers.
I did a cursory search on popular developer support sites and found that Adobe Analytics popular on Stack Overflow. If you have other developer support channels that you'd like to promote (e.g. Adobe Forums, a Slack community, Gitter, or another forum) then feel free to add it.
Adobe Analytics is the second project to adopt this new support model. You can see a live example from the [Adobe I/O Authentication …
=> Add Support and FAQ pages

docs/swagger.json
=> Updating segments endpoint to make includeType attribute customer facing

jwt.md
Improve JWT product profile and permissions information
JWT integrations are associated with profiles which govern the integration's access. The documentation was a little light on information regarding how permissions should be configured to allow proper access.
The intent is to make it easier for customers to get up and running with their JWT integrations by providing better information about how permissions should be configured.
N/A
- [] All new and existing tests passed.
=> Adding more information about profiles/permissions

calculatedmetrics.md
This change provides a user guide for the /calculatedmetrics endpoint.
Documentation for the Analtytics 2.0 /calculatedmetrics endpoint
This change has been requested so the that the endpoint is usable for our 2.0 API consumers.
This will be reviewed by the SME
- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
Not all of these apply.
=> Calculated Metrics Endpoint User Guide

reporting-tricks.md
Fixes incorrect command in the documentation
=> Incorrect command docs fix

jwt.md
Further edits to make topic consistent with others
Further changes to wording, links, grammar, and conventions to make consistent with other topics.
A bit confusing and inconsistent with other authentication topics
=> Style and clarity edit

README.md
=> Fix awkward sentence for clarity

create-oauth-client.md
=> Update topic for developer permissions

reporting-tricks.md
I have tested it and it doesn't look like the adobetools entry works any longer
=> fixing command to one that works

oauth-postman.md
I've added the tutorial video links for Postman from Adobe's Youtube channel that are easier to understand. 
The documentation is still difficult to understand for a beginner. Video tutorials are easier to understand.
The documentation is still difficult to understand for a beginner. Video tutorials are easier to understand.
Just added a new section for video links.
=> Added video tutorial links to refer for postman

discovery.md
Style Revision
I have provided a style revision of this topic including some changes in wordings, headings, formatting, and content.
See diff for wording changes
Per request
Yes to all
=> Style Revision

README.md
I added a few words to the Discovery API just to make it a bit more descriptive.
I added a few words to the Discovery API just to make it a bit more descriptive.
Yes to all.
=> Discovery API added wording

migration-guide.md
This revision includes requested content changes. I have also provided additional json examples of smaller, multiple report requests. I am grateful for any attention given to these to verify that they are correct. 
Please review @nateprice7  @mike2184  @gorrepat @stomko
=> Updated migration guide

migration-guide.md
=> adding mult breakdown link

calculatedmetrics.md, docs/swagger.json
=> AN-178562: adobe.io: calcMetrics: Review docs and expose endpoints

migration-guide.md
Additional advantages added per request. Some merged with current list. I left out the request to note "Better authentication" as 1.4 has Oauth and JWT like 2.0, unless otherwise noted in review.
Please review @ashokgorrepati and @lasser.
=> AN-182315 Advantages of API 2.0 in migration guide

docs/swagger.json
Fix swagger errors resulting from missing schema defs
https://jira.corp.adobe.com/browse/AN-186436
To solve this: https://jira.corp.adobe.com/browse/AN-186436
(Remove errors)
Tested using a swagger editor.  After changes, the errors went away
=> AN-186436: Fix broken calculated metrics in swagger

docs/swagger.json
Updating the enumeration values for ReportFilter -> type to be in camelCase instead of UPPER_CASE.
#99 
It causes confusion and non-working client libraries. 
I created a Java client library with the OpenAPI Generator and validated that with the change I was successfully able to execute calls.
=> Fixing the enumeration values for the ReportFilter -> type

docs/swagger.json
=> Update swagger.json - added includeType param to GET dateranges

docs/swagger.json
Update swagger to have better Analytics segment definitions
https://jira.corp.adobe.com/browse/AN-186732
Adds better clarity to the API Docs
Only needed for visual purposes (per JIRA requirements)
=> Add analytics segment definitions

README.md, calculatedmetrics.md, reporting-guide.md, segments-guide.md
Changed links from old help at marketing.adobe.com to new location.
=> Link fixes

reporting-tricks.md
This revision updates the document per Jira request https://jira.corp.adobe.com/browse/AN-205056. The new debugger has been documented in this update.
=> Revise for new debugger

reporting-tricks.md
Added images to the debugger revision
=> updating images

reporting-tricks.md
added disable note to the doc.
=> added note

reporting-tricks.md
=> format edit

docs/swagger.json, segments-guide.md
sistr2 is an internal testing report suite. I'm removing references from that to hopefully make things more readable.
=> Making test RSID more helpful

reporting-guide.md
=> testing warnings in adobe.io

examples/jwt/python/.gitignore, examples/jwt/python/README.md, examples/jwt/python/config.ini, examples/jwt/python/ims_client.py, examples/jwt/python/requirements.txt
This provides a sample library and instructions for interfacing with the API in python.  The code flow is patterned on the Java example.
Tested locally using using configuration values from an existing integration.
- [ x ] New feature (non-breaking change which adds functionality)
=> Adding Python JWT IMS Client Example

jwt.md
There was a excellent recent PR that provided improvements on the previous JWT example for Python. This PR simply updates the JWT readme file with a link to it.
=> Add a link to the new Pythin JWT example.

data-repair.md
- [ x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> Iterating on Data Repair API beta documentation

data-repair.md
Also, update job creation response and add additional activitymap variables.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> Add documentation for job list endpoint

reporting-guide.md
App-services team has implemented new pseudo metrics for media concurrent viewers. Added a example request and response for reference.  
N/A
New feature implementation
It has been tested with reporting service automation.
=> Added media concurrent viewers report example

bdia.md
Clarify authentication requirements
Specific call-out in operations section about Authentication header
=> Clarified authentication details

docs/swagger.json, manifest-docs.json, tags.md
Added documentation for Tags APIs which are under `componentmetadata` service
Provide usage of Tags APIs to users
Tags APIs are tested using automated tests running in component-meta-data service
=> Added documentation for Tags APIs

data-repair.md
=> Updating documentation based on beta feedback.

README.md, docs/index.html, docs/rss.json, docs/test/index.html, docs/test/rss.json, report-suites.md, vrs.md
DO NOT MERGE YET! Adding this here so it can be reviewed.
=> DO NOT MERGE YET - Adding Report Suite API documentation

data-repair.md
=> Adding reminder to verify beta registration

docs/rss.json, vrs.md
=> AN-231251:Add backgroundSessionsEnabled to vrs swagger spec

reporting-guide.md
https://jira.corp.adobe.com/browse/AN-232006
=> Add partial response information

docs/swagger.json
https://jira.corp.adobe.com/browse/AN-232006
=> Add 206 response code to /reports swagger doc

data-repair.md
=> [AN-223226] DataRepair: update doc for props, evars

data-repair.md
- Add merchandising limitation.
=> Separate limitations from usage notes.

docs/swagger.json, reporting-guide.md
Add additional reporting functionality
Add topItems endpoint for reporting use
https://jira.corp.adobe.com/browse/AN-240414
https://jira.corp.adobe.com/browse/AN-240414
=> Add topItems to reporting endpoints

bdia.md
I added a note that references the legacy dia api - requested by Justin Grover
=> Update bdia.md to add a reference to dia and made editorial changes

docs/swagger.json, manifest-docs.json, usage-logs.md
This contains the swagger spec for a new usagelog API endpoint that will exist under the Analytics Reporting APIs. I have tested the changes in the sandbox environment for the Swagger UI. Our API endpoint is in production.
=> Adding documentation for a new Analytics Reporting API - UsageLogs

data-repair.md
Adding variables (page, ip, campaign, etc)
Adding set operator
Adding filters
=> Update data repair documentation

usage-logs.md
Minor changes we want to make after a team review of this doc.
=> Add a link to the Logs tool for Usage Logs doc

bdia.md
=> Clarified 2 columns as allowed in columns, but not querystrings

manifest-api-reference.json
=> Removing beta tag

bdia.md
=> Fix page link for error handling

data-repair.md
=> Documenting doesNotContain, doesNotStartWith, doesNotEndWith

bdia.md
=> Add note about AAM integration code

segments-guide.md
Clarify segments api docs with details on segment creation, especially around the `tags` field.
#200
Clarification for future users
N/A
=> AN-261309: update segments docs about POST tags

data-repair.md
=> Updating evar docs under conversion dimensions.

bdia.md
Disallow linkType values via querystring variable
=> Linktype details

bdia.md
=> Correct pe/linkType discrepency, clarify case-sensitive customerIdType

reporting-guide.md
=> Update ReportSearch documentation

bdia.md
This throttling policy will soon be pushed to production in Adobe.IO
=> Define requests/sec limit

src/pages/guides/endpoints/data-repair/faq.md, src/pages/guides/endpoints/data-repair/index.md, src/pages/guides/endpoints/data-repair/json-body.md
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
=> Updating docs based on customer feedback

src/pages/guides/endpoints/data-repair/json-body.md
- [ x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
=> Clarifying inList filter is an exact match

src/pages/guides/endpoints/data-repair/faq.md
- [x  ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
=> Jobs can now go back 60 months

src/pages/guides/endpoints/bulk-data-insertion/faq.md
Functionality supporting this was previously updated, but we neglected to modify the documentation with the new policy.
=> Update on duplicate column policy

src/pages/guides/endpoints/bulk-data-insertion/file-format.md
BDIA has added support for UA Client Hints in the upload files
=> User Agent Client Hints support for BDIA

src/pages/guides/endpoints/bulk-data-insertion/mcseed.md
A number of customer's have had questions about the integration process. Outlining an example should assist with their workflow.
=> Adding an example workflow for MC seed integration

src/pages/guides/endpoints/bulk-data-insertion/faq.md, src/pages/guides/endpoints/bulk-data-insertion/file-format.md, src/pages/guides/endpoints/bulk-data-insertion/index.md
- BDIA file send frequency
- Client hint brands field info
=> Clarifying changes to 2 items

src/pages/guides/index.md
Updated the Auth section to include OAuth Server to Server.  Included reference to JWT end-of-life and deadline for migrating to OAuth Server to Server plus links to AdobeIO docs.
Updated the Auth section to include OAuth Server to Server.  Included reference to JWT end-of-life and deadline for migrating to OAuth Server to Server plus links to AdobeIO docs.
Adobe IO has deprecated JWT and will eol support on Jan 1, 2025
=> Update index.md to introduce OAuth Server to Server Authentication and deprecate JWT with eol notice

src/pages/guides/endpoints/data-repair/json-body.md
* multiple filters
* isNumeric/isNotNumeric
* filter variables
Please don't merge this PR yet.  It's for review.
=> Update docs to reflect features recently moved to prod

src/pages/guides/oauth.md
=> jwt to oauth

src/pages/guides/endpoints/reports/index.md
=> cleaning up

docs/classification.json, docs/index.html
This PR is adding Analytics Classification API 2.0 Swagger JSON file and updating index.html for including classification.json in the dropdown list
=> Analytics Classification API

src/pages/guides/endpoints/classifications/import-file.md, src/pages/guides/endpoints/classifications/index.md
The Classifications endpoints described in the guides seem to be wrong.
=> Fixed Classification Endpoints

docs/data_warehouse.json, docs/index.html
This API allows creating, updating, and learning about Adobe Analytics Data Warehouse Requests and Reports.
=> Add Swagger JSON For DW-API 2.0

docs/data_warehouse.json
Edits and proposed revisions are included in this PR.
=> Language review for data_warehouse.json

docs/data_warehouse.json
=> Fix 'report' -> 'request' For DW API

docs/data_warehouse.json
=> Language edits for POST examples

src/pages/guides/migration.md
This is an update to the Migration from 1.4 API guide.
=> Migration guide update

src/pages/guides/migration.md
Some additional fixes to the Migration Guide
=> Some additional fixes

src/pages/guides/use-cases/media-edge/chapters-with-ad-timeline.md
=> adding diagram language

src/pages/guides/endpoints/classifications/index.md
=> get job dataset update index.md

docs/datasources.json, docs/index.html
This PR is adding Analytics Data Sources API 2.0 Swagger JSON file and updating index.html for including datasources.json in the dropdown list
=> AN-343219: Add analytics data sources 2.0 API json file

src/pages/guides/endpoints/data-sources/index.md
Create folder and index for data sources guide
=> Create data sources

docs/data-feeds.json
Datafeeds API 2.0 doc
Swagger.json for new Datafeeds API
=> Datafeeds API

yarn.lock
Reverts AdobeDocs/analytics-2.0-apis#500
=> Revert "Bump ws from 5.2.3 to 5.2.4"

docs/data-feeds.json
Restructuring Datafeeds JSON response
=> Restructuring datafeeds

docs/data_feeds.json
=> Datafeeds API swagger update

src/pages/guides/endpoints/livestream/index.md
=> url updates

docs/data_feeds.json
* Remove /health endpoint
* Change the adobeIO URL from data_feeds to data_feed
* Remove x-global-proxy-company-id param as a required param from endpoints as that comes in from the AdobeIO header after sign-in
* Remove unused Schemas
- [ x] I have reviewed and signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] I have read and agree to the [CONTRIBUTING](CONTRIBUTING.md) document.
=> [DF-API] Swagger update

docs/data_feeds.json
=> [DF-API] Rename endpoints

docs/index.html, src/pages/guides/migration.md
- [x ] I have reviewed and signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] I have read and agree to the [CONTRIBUTING](CONTRIBUTING.md) document.
=> [DF-API] Change drop down option to singular

docs/data_feeds.json
=> [DF-API] Fix duplicate endpoint bug

docs/data_feeds.json
=> [DF-API] Change the HTTP method for Manage API

src/pages/guides/endpoints/data-feed/index.md
=> update df part 2

src/pages/guides/endpoints/data-feed/index.md
=> remove200.md

docs/data_feeds.json
=> [DF-API] Add the datafeedExtendedView for get feed by id

docs/data_feeds.json
=> [DF-API] Remove unneccessary x-user-auth. Caused CORS issues.

docs/data_feeds.json
- [ x] I have reviewed and signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x ] I have read and agree to the [CONTRIBUTING](CONTRIBUTING.md) document.
=> [DF-API] Document 400 errors

docs/data_feeds.json
=> Add missing params and erros

src/pages/guides/endpoints/data-feed/index.md
- [x ] I have reviewed and signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] I have read and agree to the [CONTRIBUTING](CONTRIBUTING.md) document.
=> Document Review

src/pages/guides/endpoints/compmigration/index.md
=> migration changes

docs/swagger.json
=> AN-372897:Add attributionModel expansion to /dimensions

docs/cloud-locations.json
Add new endpoint for cloud locations api to get S3 user are
=> [CLOUD-LOCATIONS]Add endpoint to get s3 user arn

docs/cloud-locations.json
Remove duplicated response object
=> [CLOUD-LOCATIONS] Remove duplicated object

static/cja-migration.json
=> AN-377342 - added bulk migration endpoints for migration and status

static/report-suites.json
Adding a new POST endpoint to create a report suite, as discussed in a previous call.  Net new endpoint with minor restructuring of existing sections.
=> Add new 2.0 endpoint for create report suite endpoint
